### ISSUE TITLE
firmware editing

### ISSUE THREAD

**Issue by orangecms** [ISpillMyDrink/UEFI-Repair-Guide#1]
Hey, the wiki here is awesome!

I'm the author of https://github.com/fiedka/fiedka and working on tooling for firmware editing. I'd love to exchange a bit and see how some things can be improved with Fiedka, which is in part based on https://github.com/linuxboot/fiano.

Please let me know if you'd like to exchange, thank you! :)

**Comment by ISpillMyDrink** [comment]
Exchange is always welcome as are contributions to the wiki. Best way to get in touch is via email at admin@socialz.de as not to spam the Issues section which I'd like to reserve for corrections and requests for clarification. Thanks! :)
